name: safe_environment
description: "A plugin fot check the integrity device."
version: 1.0.0
homepage: https://github.com/ArZHa03/safe_environment

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.arzha.safe_environment
        pluginClass: SafeEnvironmentPlugin
      ios:
        pluginClass: SafeEnvironmentPlugin
